<?php

echo $this->uiLinkIconButton(getenv('REQUEST_URI').'model', 'Generate Model Class from Table', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'list', 'Generate UiTable Class from Table', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'form', 'Generate UiForm Class from Table', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'controller', 'Generate Controller Class from Table', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'dbtable', 'Generate DB_Table Class from Table', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'view-list', 'Generate list.phtml', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'view-add', 'Generate add.phtml', 'circle-plus');
echo '<br/><br/>';
echo $this->uiLinkIconButton(getenv('REQUEST_URI').'view-edit', 'Generate edit.phtml', 'circle-plus');
